### ISSUE TITLE
Error in training 12-net

### ISSUE THREAD

**Issue by mariamallaa** [mks0601/Face_detection#21]
Hi, when trying to run train_12net.py I'm getting the error:
Loading positive training db...
Loading negative training db...
Traceback (most recent call last):
  File "train_12net.py", line 16, in <module>
    net_12 = model.detect_12Net(input_12_node,target_12_node)
  File "D:\GP\A-Convolutional-Neural-Network-Cascade-for-Face-Detection-master\A-Convolutional-Neural-Network-Cascade-for-Face-Detection-master\model.py", line 45, in __init__
    self.conv2_shape = tf.concat(0,[[-1],[tf.reduce_prod(tf.slice(tf.shape(self.h_conv2),[1],[3]),0)]])
  File "C:\Users\Mariam Alaa\.conda\envs\opencv\lib\site-packages\tensorflow\python\util\dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "C:\Users\Mariam Alaa\.conda\envs\opencv\lib\site-packages\tensorflow\python\ops\array_ops.py", line 1604, in concat
    dtype=dtypes.int32).get_shape().assert_has_rank(0)
  File "C:\Users\Mariam Alaa\.conda\envs\opencv\lib\site-packages\tensorflow\python\framework\tensor_shape.py", line 997, in assert_has_rank
    raise ValueError("Shape %s must have rank %d" % (self, rank))
ValueError: Shape (2, 1) must have rank 0

Please can you help me?

**Comment by mariamallaa** [comment]
Okay I solved the issue by replacing
 self.conv2_shape = tf.concat(0,[[-1],[tf.reduce_prod(tf.slice(tf.shape(self.h_conv2),[1],[3]),0)]])
by 
self.conv2_shape = tf.concat([[-1],[tf.reduce_prod(tf.slice(tf.shape(self.h_conv2),[1],[3]),0)]],0)
